### ISSUE TITLE
Forbid comments in user query.

### ISSUE THREAD

**Issue by lenguyenthedat** [zalora/redsift#13]
Currently, we enforce limit on user query result to 100 entries
(ref: https://github.com/zalora/redsift/blob/master/Redsift/DB.hs#L153)

Unfortunately, this doesn't work if user try to put comments at the end of the query:
![screen shot 2014-06-11 at 11 42 49](https://cloud.githubusercontent.com/assets/1543321/3240065/aad7fe36-f11c-11e3-8efc-37983c00a245.png)

**Comment by lenguyenthedat** [comment]
Is this fixed, or is it not relevant anymore?

**Comment by ip1981** [comment]
no, yes (it is relevant) :-)

**Comment by lenguyenthedat** [comment]
Will it ever be fixed or is this project abandoned? :(
