### ISSUE TITLE
Redsift Export email message: html hyperlink broken

### ISSUE THREAD

**Issue by asokratis** [zalora/redsift#41]
Has to do with the hyperlink of the download link being broken (but the actual text link if its copied and pasted on the browser manually will direct you to the correct download link).

Temporary way to solve it is to not hyperlink it or end users will get confused.

> @soenkehahn said "I'm guessing that the email is not html but plaintext and that some mail clients (gmail?) add the hyperlink (and do so incorrectly in this case). Still, maybe redsift could do something smarter here?"

**Comment by fmap** [comment]
Image from the misplaced issue: 

![](https://cloud.githubusercontent.com/assets/7789501/5594177/2141cdb8-91f4-11e4-9fae-d52fe7f8cc23.png)

I count eighty characters on the first line of the URL, so this is likely convention gone astray. If consistent, maybe wrapping the URL in `<`, `>` will work, can test with `text/plain` messages from another client and Gmail (?).

**Comment by lenguyenthedat** [comment]
> Update: works in Gmail, need details on client; plausibly Outlook given typeface.

I suppose it's not a problem with Redsift per se. Should this be closed?
